#!/bin/bash
echo "*********************************************************"
echo "Running git pre-push hook. Running unit tests... "
echo "*********************************************************"

./gradlew testDebugUnitTest

status=$?

if [ "$status" = 0 ] ; then
    echo "Unit tests passed successfully."
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "Unit tests failed"
    echo "Please ensure tests pass before pushing. Run './gradlew test' to run unit tests locally"
    echo "*********************************************************"
    exit 1
fi
